const { PDFDocument, rgb, StandardFonts } = require("pdf-lib");

module.exports = async (req, res) => {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const { role, type, sections, userName, userInstitution,
            academicYear, subjects, pageSize, orientation } = req.body;

    if (!userName || !sections?.length) {
      return res.status(400).json({ error: "Missing required fields." });
    }

    const PAGE_SIZES = {
      A4:         [595, 842],
      A3:         [842, 1191],
      A5:         [420, 595],
      Letter:     [612, 792],
      LetterLand: [792, 612],
      Legal:      [612, 1008],
    };

    let [W, H] = PAGE_SIZES[pageSize] || PAGE_SIZES["A4"];
    if (orientation === "landscape") [W, H] = [H, W];

    const pdfDoc      = await PDFDocument.create();
    const boldFont    = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const regularFont = await pdfDoc.embedFont(StandardFonts.Helvetica);

    const C = {
      primary : rgb(0.18, 0.38, 0.72),
      light   : rgb(0.90, 0.93, 0.98),
      muted   : rgb(0.5,  0.5,  0.5),
      dark    : rgb(0.1,  0.1,  0.1),
      white   : rgb(1,    1,    1),
      yellow  : rgb(0.99, 0.95, 0.75),
      pink    : rgb(0.98, 0.88, 0.93),
      gray    : rgb(0.95, 0.95, 0.95),
    };

    function hLine(page, y, x1, x2, color = C.muted, thickness = 0.5) {
      page.drawLine({ start: { x: x1, y }, end: { x: x2, y }, thickness, color });
    }

    function rect(page, x, y, w, h, color) {
      page.drawRectangle({ x, y, width: w, height: h, color });
    }

    function txt(page, text, x, y, size, font, color = C.dark) {
      try {
        page.drawText(String(text), { x, y, size, font, color });
      } catch(e) {}
    }

    function addHeader(page, title, userName, boldFont, regularFont, W, H) {
      rect(page, 0, H - 52, W, 52, C.primary);
      txt(page, title, 36, H - 34, 16, boldFont, C.white);
      txt(page, userName, W - 180, H - 34, 9, regularFont, C.white);
    }

    // Cover Page
    const cover = pdfDoc.addPage([W, H]);
    rect(cover, 0, 0, W, H, C.primary);
    rect(cover, 24, 24, W - 48, H - 48, C.white);
    rect(cover, 24, H - 90, W - 48, 66, C.primary);
    txt(cover, "PLANNER GENERATOR", W / 2 - 80, H - 58, 18, boldFont, C.white);
    txt(cover, role.toUpperCase(), W / 2 - 30, H - 76, 10, regularFont, C.white);
    txt(cover, userName, W / 2 - 60, H - 145, 18, boldFont, C.dark);
    txt(cover, userInstitution || "", W / 2 - 60, H - 170, 11, regularFont, C.muted);
    txt(cover, academicYear || "", W / 2 - 40, H - 190, 10, regularFont, C.muted);
    txt(cover, "Compatible with iPad, Tablets, iPhone & Smartphones",
      W / 2 - 115, 62, 8, regularFont, C.muted);
    txt(cover, "Generated by Planner Generator  -  " + new Date().toLocaleDateString(),
      W / 2 - 100, 46, 8, regularFont, C.muted);

    const pdfBytes = await pdfDoc.save();
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition",
      `attachment; filename=planner-${userName.replace(/\s+/g, "_")}.pdf`);
    res.send(Buffer.from(pdfBytes));

  } catch (err) {
    console.error("PDF error:", err.message);
    res.status(500).json({ error: err.message });
  }
};